# https://taskfile.dev

version: "3"

vars:
  PORT: "4000"

tasks:
  default:
    cmds:
      - "bundle install"
      - "bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload"
    silent: true
